// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type AccountMember struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	LoginID   string    `json:"login_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type EmailAllowlist struct {
	ID        int64     `json:"id"`
	Pattern   string    `json:"pattern"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type Login struct {
	ID        string    `json:"id"`
	GoogleID  string    `json:"google_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID            string         `json:"id"`
	LoginID       sql.NullString `json:"login_id"`
	AccountID     sql.NullString `json:"account_id"`
	Email         sql.NullString `json:"email"`
	Authenticated bool           `json:"authenticated"`
	OauthState    sql.NullString `json:"oauth_state"`
	ReturnUrl     sql.NullString `json:"return_url"`
	CreatedAt     time.Time      `json:"created_at"`
	LastAccessed  time.Time      `json:"last_accessed"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

type Trifle struct {
	ID          string         `json:"id"`
	AccountID   string         `json:"account_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullString `json:"parent_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type TrifleFile struct {
	ID        string    `json:"id"`
	TrifleID  string    `json:"trifle_id"`
	Path      string    `json:"path"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
